name: CI/CD Pipeline

on: [push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
          sudo pip install -r requirements.txt
          python -m pip install --upgrade pip


    - name: Build Docker image
      run: docker-compose build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy to production
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }} 
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker-compose down
          docker-compose up -d 
