name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker-compose build

    - name: Test
      run: docker-compose run web python -m pytest tests/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy to production
      run: |
        docker-compose down
        docker-compose up -d

