name: CI/CD Pipeline

on: [push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
          sudo pip install -r requirements.txt
          python -m pip install --upgrade pip


    - name: Build Docker image
      run:  docker-compose builD

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy to production
      uses: appleboy/ssh-action@master

    - name: Docker-compose build
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }} 
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        run: |
          sudo docker-compose up
          docker-compose up -d 
